#spring.application.name=tesis
spring.datasource.url=jdbc:mysql://localhost:3306/programminguat_db?createDatabaseIfNotExist=true
#Agregar usuario de tu servidor sql local
spring.datasource.username=
#Agregar contraseña de tu servidor sql local
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081

#CUENTA CMED
#Ingresar credenciales de la cuenta de Jdoodle
jdoodle.client.id=
jdoodle.client.secret=

#url de la API
jdoodle.api.url=